ibw_jobeet_ibw_category:
#    path： /category/{slug}
#    defaults: { _controller: IbwJobeetBundle:Category:show }
    resource: "@IbwJobeetBundle/Resources/config/routing/category.yml"
    prefix: /category

ibw_jobeet_ibw_job:
    resource: "@IbwJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

ibw_jobeet_homepage:
    path:     /
    defaults: { _controller: IbwJobeetBundle:Job:index }
