ibw_jobeet_ibw_category:
#    path： /category/{slug}
#    defaults: { _controller: IbwJobeetBundle:Category:show }
    resource: "@IbwJobeetBundle/Resources/config/routing/category.yml"
    prefix: /category

ibw_jobeet_ibw_job:
    resource: "@IbwJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

ibw_jobeet_homepage:
    path:     /{_locale}/
    defaults: { _controller: IbwJobeetBundle:Job:index }
    requirements:
      _locale: en|zh

login:
    path: /login
    defaults: {_controller: IbwJobeetBundle:Default:login}

login_check:
    path: /login_check

logout:
    path: /logout

IbwJobeetBundle_category:
    pattern: /{_locale}/category/{slug}/{page}
    defaults: { _controller: IbwJobeetBundle:Category:show, page: 1 }
    requirements:
      _locale: en|zh

IbwJobeetBundle_api:
    path: /api/{token}/jobs.{_format}
    defaults: {_controller: "IbwJobeetBundle:Api:list"}
    requirements:
        _format: xml|json|yaml|yml

ibw_jobeet_affiliate:
    resource: "@IbwJobeetBundle/Resources/config/routing/affiliate.yml"
    prefix: /{_locale}/affiliate
    requirements:
      _locale: en|zh

IbwJobeetBundle_changeLanguage:
  path: /change_language
  defaults: { _controller: 'IbwJobeetBundle:Default:changeLanguage'}


IbwJobeetBundle_nonlocalized:
  path: /
  defaults: { _controller: "IbwJobeetBundle:Job:index"}