services:
#    ibw_jobeet.example:
#        class: Ibw\JobeetBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    ibw.jobeet.admin.category:
        class: Ibw\JobeetBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 管理, label: 类别管理(category) }
        arguments:
            - ~
            - Ibw\JobeetBundle\Entity\Category
            - 'IbwJobeetBundle:CategoryAdmin'
    ibw.jobeet.admin.job:
        class: Ibw\JobeetBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 管理, label: 职位管理(job) }
        arguments:
            - ~
            - Ibw\JobeetBundle\Entity\Job
            - 'IbwJobeetBundle:JobAdmin'

    ibw.jobeet.admin.affiliate:
        class: Ibw\JobeetBundle\Admin\AffiliateAdmin
        tags:
            - { name: sonata.admin, manager_type:orm, group: jobeet, label: (机构)Affiliates}
        arguments:
            - ~
            - Ibw\JobeetBundle\Entity\Affiliate
            - 'IbwJobeetBundle:AffiliateAdmin'
